<?php

namespace App\Http\Repositories;

use App\Models\PlatformReporttag;
use App\Models\PlatformCharm;
use App\Repositories\BaseRepository;

/**
 * 魅力管理
 * Class PlatformCharmRepository
 * @package App\Http\Repositories
 */
class PlatformCharmRepository extends BaseRepository
{
    public function model()
    {
        return PlatformCharm::class;
    }

    public function lists($addWhere = null)
    {
        $where = function ($query) {
            if (request('key')) {
                $query->where(function ($query) {
                    $query->where('name', 'like', '%' . request('key') . '%');
                });
            }
            if (request('status') != null) {
                $query->where('status', request('status'));
            }
        };
        $this->where($where);
        if ($addWhere) {
            $this->where($addWhere);
        }
        $perPage = request('size');
        if ($perPage) {
            return parent::paginate($perPage);
        }
        return parent::paginate();
    }
public function store(array $data)
{
    unset($data['file']);
    return parent::store($data); // TODO: Change the autogenerated stub
}
}

